Managing planet feature files
kapoole/TeamPlutoPlanetarium pull request #12
Opened 2024-11-11 23:49 UTC by light1804

Need a quick review for Manage planet feature file before merge

2024-11-12 00:20 UTC, kapoole requested changes

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/AddPlanet.feature
> +        When the User enter new <planet name> with no more than 30 characters
"When the User enters '<'Planet Name'>'" since this is testing both unique name and character limit test cases in one scenario

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/AddPlanet.feature
> +        Then the User see <alert message >
Make sure to add the word "should" to Then statements in Gherkin.

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/AddPlanet.feature
> +        And the user verify <planet added or not added> in the list
I think you can delete this And statement.

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/AddPlanet.feature
> +        And the User redirects to <Home Page>
"And the User should '<'Add Planet Redirect'>'"

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +    Validating that Planets can be deleted by users no matter if the Planets have any orbiting Moons or not.
I would be more descriptive in this Validating... statement. You can use multiple sentences and it should be clear about all the requirements for different inputs. Not only should it work if Planets have moons or not but also what is the result if there are moons that orbit the planet.

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        And the User enter  <planet name>
Switch the "When" and "And" between lines 7 and 8.

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        When clicks Delete Button
This should be And

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        And the User see <alert message >
This should be Then

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        Then the User redirects to <Home Page>
"And the User '<'Delete Moon Redirect'>'"

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        And the User see <alert message >
More specific <alert message> would be "Then the User should see an alert saying '<'Delete Planet Result'>'"

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/AddPlanet.feature
> +        Then the User see <alert message >
More specific <alert message> would be "Then the User should see alert saying '<'Add Planet Result'>'"

2024-11-12 00:20 UTC, kapoole commented on AutomatedTesting/src/test/resources/features/DeletePlanet.feature
> +        When the user verify <planet own by User or not  own by User> in the list
I think this line can be deleted.

2024-11-12 03:54 UTC, light1804 reviewed
As commented changes have been made. Please review

2024-11-14 22:40 UTC, kapoole approved these changes
LGTM

2024-11-14 22:41 UTC, merged